# 1. Diciamo a Spring di attivare il profilo "dev"
spring.profiles.active=dev

#---
# 2. Qui iniziano le configurazioni specifiche per il profilo "dev"
spring.config.activate.on-profile=dev

# Usa H2 in memoria
spring.datasource.url=jdbc:h2:mem:gestionaledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Abilita la console web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra i comandi SQL che Spring invia al DB
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Security JWT
jwt.secret=QuestaEUnaChiaveSegretaMoltoLungaEComplessaCheDeveAvereAlmeno256BitPerEssereSicura123!
jwt.expiration=86400000