# Usa H2 in memoria
spring.datasource.url=jdbc:h2:mem:gestionaledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Abilita la console web (per vedere le tabelle nel browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra i comandi SQL che Spring invia al DB (utile per imparare)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update